### ISSUE TITLE
Locale US.UTF-8 missing

### ISSUE THREAD

**Issue by lluked** [cowrie/docker-cowrie#15]
When building the image the following is outputted.
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US.UTF-8",
        LC_ALL = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

Is 
```
ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
```
still required in the Dockerfile to resolve issues mentioned? 

Running locale -a within the debian:buster-slim container shows
```
C
C.UTF-8
POSIX
```
are available, should we use  C.UTF-8 instead or do we need to install en_US.UTF-8 to prevent any issues?

Thanks,
Luke

**Comment by micheloosterhof** [comment]
That locale change was added in https://github.com/cowrie/docker-cowrie/issues/8
But not for perl, so I don't think it needs to change now. The `C.UTF-8` locale is new to me, could give that a try.

**Comment by lluked** [comment]
Thanks for the details, everything seems to be working fine as is, I just saw the output in the logs and wasn't sure.
