### ISSUE TITLE
line 25: DEPLOY_KEY: unbound variable

### ISSUE THREAD

**Issue by Woolfy025** [cowrie/docker-cowrie#17]
I keep getting this error while trying to run the 'stingar/cowrie' docker version of cowrie on a Raspberry pi 4 / armv7 install.

This command:  sudo docker run stingar/cowrie:master
 
All I can read up on it is that it relates to a ssh key on the developers side of the project of github? 

This was the website I got it from:

https://hub.docker.com/r/stingar/cowrie/tags

Using this:  docker pull stingar/cowrie:master

I'm not sure how else to fix it on my side of things. Hopefully this is the correct github page to post this as well.

**Comment by micheloosterhof** [comment]
Hi! Sorry this is not the correct page to post, you'd have to speak to the owner of the stingar account.

**Comment by Woolfy025** [comment]
Thanks for the update! I'm not sure on how to get a hold of him but I'll see what I can find.
