### ISSUE TITLE
Needs Update on Docker Image on Docker Hub 

### ISSUE THREAD

**Issue by mr-wacker** [cowrie/docker-cowrie#23]
MySQL module is operational only if you build a docker container from the source by git clone. 

The fix is already done by last commit [aa65a14](https://github.com/cowrie/docker-cowrie/commit/aa65a14bd2fe41a428dad0eb9aa8ff3940cb5253)

However, on [Docker hub ](https://hub.docker.com/r/cowrie/cowrie/dockerfile) the last updated was 3 months ago. 

Can you push an updated docker container?

**Comment by micheloosterhof** [comment]
hi!
I did a rebuild on docker hub. This is supposed to go automatic, but somethings wrong with the CI pipeline. I'll take a look at that as well.
